version: '3'

services: 
  app:
    image: app-report-image
    container_name: app-report
    build: .
    privileged: true
    volumes:
      - .:/usr/src/
    ports:
      - "3011:3011" 
    command: "yarn start"
    